using PitakaApp.Api.Enums;
using PitakaApp.Api.Models;

namespace PitakaApp.Api.Actions;

public class GenerateTransaction
{
    public static Transaction GetTransaction(RecurringTransaction recurringTransaction, DateTime transactionDate)
    {
        return new Transaction
        {
            UserId = recurringTransaction.UserId,
            AccountId = recurringTransaction.AccountId,
            CategoryId = recurringTransaction.CategoryId,
            Amount = recurringTransaction.Amount,
            TransactionDate = transactionDate,
            Description = $"Generated by recurring transaction: {recurringTransaction.Name}",
            RecurringTransactionId = recurringTransaction.Id,
            Type = recurringTransaction.Type switch
                {
                    RecurringTransactionType.Income => TransactionType.Income,
                    RecurringTransactionType.Expense => TransactionType.Expense,
                    _ => throw new InvalidOperationException($"Unmapped recurring transaction type: {recurringTransaction.Type}")
                },
        };
    }
}